// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// preprocess_dates
DataFrame preprocess_dates(CharacterVector dates, int forecast_months);
RcppExport SEXP _RecipeExplorer_preprocess_dates(SEXP datesSEXP, SEXP forecast_monthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    Rcpp::traits::input_parameter< int >::type forecast_months(forecast_monthsSEXP);
    rcpp_result_gen = Rcpp::wrap(preprocess_dates(dates, forecast_months));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RecipeExplorer_preprocess_dates", (DL_FUNC) &_RecipeExplorer_preprocess_dates, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RecipeExplorer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
