# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

preprocess_dates <- function(dates, forecast_months) {
    .Call('_RecipeExplorer_preprocess_dates', PACKAGE = 'RecipeExplorer', dates, forecast_months)
}

